config/routes.rb
Smarty::Application.routes.draw do
  resources :linea_items

  resources :line_items

  resources :carts

  get "store/index"

  resources :smarts    # si esta comentado no muestra en consola el rake route
  root :to => "store#index", :as => 'store'

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, :dependent => :destroy  # crea ciertos metodos en el modelo

  def total_amount

    #total = 0
    #line_items.each do |line_item|
    #  total += line_item.smart.price
    #end

    #return total
    total_amount = Smart.joins(:line_items)
      .where(:line_items => {:cart_id => self.id})
        .sum(:price)
    total_amount.to_f
  end
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :cart
  belongs_to :smart
end

app/models/smart.rb
class Smart < ActiveRecord::Base

  validates :name, :uniqueness => true
  #validates :name, :presence =>
  validates :name, :presence => {:message => "Ingresar datos "}

  validates :description, :length => {:minimum => 20, :message => "debe tener como minimo 20 caracteres"}
  validates :price, :numericality => {:greater_than_or_equal_to => 0.01, :message => "debe ser mayor a 0"}

  validates :image_url, :format => {
        :with => /\.(gif|jpg|png)$/i,
        :message => "debe ser una URL, una imagen gif o png "
    }
  has_many :line_items
  before_destroy :ensure_not_referenced_by_any_line_item
  def ensure_not_referenced_by_any_line_item
    #Si existe item en linea item muestra un error
    if line_items.first        #empty?
      #agrega un mensaje de error a nivel del objeto, no a nivel del atributo
      errors.add(:base,"La linea de Item esta presente")
      return false
    else
      return true
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  protected
  def current_cart
    cart_id = session[:cart_id]
      if cart_id.nil?
        cart = Cart.create;
        session[:cart_id] = cart.id
      else
        cart=Cart.find ( session[:cart_id])
      end
    return cart
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  # GET /carts
  # GET /carts.xml
  def index
    @carts = Cart.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @carts }
    end
  end

  # GET /carts/1
  # GET /carts/1.xml
  def show
    @cart = Cart.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @cart }
    end
  end

  # GET /carts/new
  # GET /carts/new.xml
  def new
    @cart = Cart.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @cart }
    end
  end

  # GET /carts/1/edit
  def edit
    @cart = Cart.find(params[:id])
  end

  # POST /carts
  # POST /carts.xml
  def create
    @cart = Cart.new(params[:cart])

    respond_to do |format|
      if @cart.save
        format.html { redirect_to(@cart, :notice => 'Cart was successfully created.') }
        format.xml  { render :xml => @cart, :status => :created, :location => @cart }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @cart.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /carts/1
  # PUT /carts/1.xml
  def update
    @cart = Cart.find(params[:id])

    respond_to do |format|
      if @cart.update_attributes(params[:cart])
        format.html { redirect_to(@cart, :notice => 'Cart was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @cart.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.xml
  def destroy
    @cart = Cart.find(params[:id])
    @cart.destroy

    respond_to do |format|
      format.html { redirect_to(carts_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController

  def index
    @line_items = LineItem.all

    respond_to do |format|
      format.html
      format.xml  { render :xml => @line_items }
    end
  end

  # GET /line_items/1
  # GET /line_items/1.xml
  def show
    @line_item = LineItem.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @line_item }
    end
  end

  # GET /line_items/new
  # GET /line_items/new.xml
  def new
    @line_item = LineItem.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @line_item }
    end
  end

  # GET /line_items/1/edit
  def edit
    @line_item = LineItem.find(params[:id])
  end

  # POST /line_items
  # POST /line_items.xml
  def create
     @cart = current_cart
     smart = Smart.find(params[:smart_id])


    @line_item = LineItem.create(:smart => smart, :cart => @cart)

    respond_to do |format|
      if @line_item.save
        format.html {redirect_to(store_path,
                                  :notice => 'Line item was successfully created.') }
        format.xml  {render :xml => @line_item,
                             :status => :created, :location => @line_item }

        format.js  # create.js.erb ()mismo nombre que el action actual)

      else
        format.html {redirect_to(store_path,
                              :notice => "Smart no pudo adherir al carrito" )}
        format.xml  {render :xml => @line_item.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /line_items/1
  # PUT /line_items/1.xml
  def update
    @line_item = LineItem.find(params[:id])

    respond_to do |format|
      if @line_item.update_attributes(params[:line_item])
        format.html { redirect_to(@line_item, :notice => 'Line item was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @line_item.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1
  # DELETE /line_items/1.xml
  def destroy
    @line_item = LineItem.find(params[:id])
    @line_item.destroy

    respond_to do |format|
      format.html { redirect_to(line_items_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/smarts_controller.rb
class SmartsController < ApplicationController
  # GET /smarts
  # GET /smarts.xml
  def index
    @smarts = Smart.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @smarts }
    end
  end

  # GET /smarts/1
  # GET /smarts/1.xml
  def show
    @smart = Smart.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @smart }
    end
  end

  # GET /smarts/new
  # GET /smarts/new.xml
  def new
    @smart = Smart.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @smart }
    end
  end

  # GET /smarts/1/edit
  def edit
    @smart = Smart.find(params[:id])
  end

  # POST /smarts
  # POST /smarts.xml
  def create
    @smart = Smart.new(params[:smart])

    respond_to do |format|
      if @smart.save
        format.html { redirect_to(@smart, :notice => 'Smart was successfully created.') }
        format.xml  { render :xml => @smart, :status => :created, :location => @smart }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @smart.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /smarts/1
  # PUT /smarts/1.xml
  def update
    @smart = Smart.find(params[:id])

    respond_to do |format|
      if @smart.update_attributes(params[:smart])
        format.html { redirect_to(@smart, :notice => 'Smart was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @smart.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /smarts/1
  # DELETE /smarts/1.xml
  def destroy
    @smart = Smart.find(params[:id])
    @smart.destroy

    respond_to do |format|
      format.html { redirect_to(smarts_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  def index
    @smarts = Smart.all
    @page_title = "Shopping"
    @cart = current_cart
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/linea_items_helper.rb
module LineaItemsHelper
end

app/helpers/smarts_helper.rb
module SmartsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/carts/_cart.html.erb
  <%#contenedor de campo dentro del layout y lo que se muev al partial lo que esta adentro %>

  <h3> <%= message %> </h3>

  <ul id="cart">
        <%#  <% @cart.line_items.each do |line_items| %>
        <% cart.line_items.each do |line_items| %>
            <li>
                                <%= line_items.smart.name %>
                                |
                                <%= line_items.smart.price %>
            </li>
           <% end %>

    </ul>

    <div> Total =$ <%= cart.total_amount %>  </div>

    <%#  <div> Total =$  <% @cart.total_amount <h3>  </div>   %>

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<h1>Listing carts</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @carts.each do |cart| %>
  <tr>
    <td><%= link_to 'Show', cart %></td>
    <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
    <td><%= link_to 'Destroy', cart, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_cart_path(@cart) %> |
<%= link_to 'Back', carts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Smarty by Bancard</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body id= "store">
    <div id="banner" >
      <%= @page_tittle || "SmartyStore" %>
      <%= image_tag("logo_256.png", :height => 64, :width => 64)%>
    </div>
    <div id= "columns">

        <div id="side">

            <div>
                <a href="#">Home</a>
                <a href="#">Questions</a>
                <a href="#">News</a>
                <a href="#">Contact</a>
            </div>
            <div id= "cart">
                <% if @cart %>
                   <%= render @cart, :message => 'Carrito de compras'  %>
                        <%# locals = variable local del partial
                        # :cart = nombre de variable dentro del partial %>
                <% end %>
            </div>
              <%# agregar el total de la compra %>

        <div id="main">
             <%= yield %>
        </div>
        <div class="clear"> </div>
    </div>


</body>
</html>

app/views/line_items/_form.html.erb
<%= form_for(@line_item) do |f| %>
  <% if @line_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
      <% @line_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :smart_id %><br />
    <%= f.text_field :smart_id %>
  </div>

  <div class="field">
    <%= f.label :cart_id %><br />
    <%= f.text_field :cart_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/line_items/create.js.erb
<%#alert(1000)

    1) buscar el elemento html contenedor del carrito
    2) modificar el html de ese elemnto

    %>

// 1
// jQuery('#cart').html("Se ha agrego el producto");

<%
 cart_html = render @cart, :message => 'carrito de compras'
 %>

jQuery('#cart').html("<%= escape_javascript(cart_html) %> ");

// procedimiento java script
jQuery('#cart').animate(
        {opacity: 0.20},
        2000, // milisegundos
        function() {
            jQuery('#cart').animate(
                    {opacity : 1},
                    3000
            );
        }
);

app/views/line_items/edit.html.erb
<h1>Editing line_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @line_item %> |
<%= link_to 'Back', line_items_path %>

app/views/line_items/index.html.erb
<h1>Listing line_items</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @line_items.each do |line_item| %>
  <tr>
    <td><%= line_item.id %></td>
    <td><%= link_to 'Show', line_item %></td>
    <td><%= link_to 'Edit', edit_line_item_path(line_item) %></td>
    <td><%= link_to 'Destroy', line_item, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Line item', new_line_item_path %>

app/views/line_items/new.html.erb
<h1>New line_item</h1>

<%= render 'form' %>

<%= link_to 'Back', line_items_path %>

app/views/line_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Cart id:</b>
  <%= @line_item.cart.id %>
</p>

<p>
  <b>Smart:</b>
  <%= @line_item.smart.name %>
</p>

<%= link_to 'Edit', edit_line_item_path(@line_item) %> |
<%= link_to 'Back', line_items_path %>

app/views/smarts/_form.html.erb
<%= form_for(@smart) do |f| %>
  <% if @smart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@smart.errors.count, "error") %> prohibited this smart from being saved:</h2>

      <ul>
      <% @smart.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br />
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/smarts/edit.html.erb
<h1>Editing smart</h1>

<%= render 'form' %>

<%= link_to 'Show', @smart %> |
<%= link_to 'Back', smarts_path %>

app/views/smarts/index.html.erb
<h1>Listing smarts</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Image url</th>
    <th>Price</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @smarts.each do |smart| %>
  <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
    <td><%= smart.name %></td>
    <td><%= smart.description %></td>
    <td><%= image_tag(smart.image_url) %></td>
    <td><%= smart.price %></td>
    <td><%= link_to 'Show', smart %></td>
    <td><%= link_to 'Edit', edit_smart_path(smart) %></td>
    <td><%= link_to 'Destroy', smart, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Smart', new_smart_path %>

app/views/smarts/new.html.erb
<h1>New smart</h1>

<%= render 'form' %>

<%= link_to 'Back', smarts_path %>

app/views/smarts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @smart.name %>
</p>

<p>
  <b>Description:</b>
  <%= @smart.description %>
</p>

<p>
  <b>Image url:</b>
  <%= @smart.image_url %>
</p>

<p>
  <b>Price:</b>
  <%= @smart.price %>
</p>


<%= link_to 'Edit', edit_smart_path(@smart) %> |
<%= link_to 'Back', smarts_path %>

app/views/store/index.html.erb
<title> Smarty </title>
<h1>Smarts Phone Store</h1>
<div id= "smarts">
  <% @smarts.each do |smart| %>
  <div class ="smart">

    <div class="image">
      <%= image_tag(smart.image_url, :height => "100" ) %>
    </div>

    <div class="content">
        <h2>
         <%= smart.name %>
        </h2>
        <p>
            <%= smart.description %>
        </p>
    </div>

    <div class="price">
      <div>
            <%= smart.price %>
      </div>
      <div>
        <%=button_to "Comprar", line_items_path(:smart_id => smart.id), :remote => true %>
      </div>
                <%#agregar el boton de comprar%>

    </div>

    <div class="clear"></div>
   </div>
   <%end %>
</div>